#!/bin/zsh -f

# For tramp et al., don't do anything fancy.
if [[ "$TERM" == "dumb"  ]]
then
  unsetopt zle
  unsetopt prompt_cr
  unsetopt prompt_subst
  unfunction precmd
  unfunction preexec
  PS1='$ '
  return
fi

source ~/dotfiles/configs/.zsh_functions

# Reattach or start a new Tmux.
# This function name is short because I want to call it this way
# interactively.
t

# Path to your dotfiles installation.
export DOTFILES=$HOME/dotfiles

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set my terminal if I'm not in tmux.
[[ "$TMUX" == "" ]] && TERM=xterm-256color

# Disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Disable command autocorrection.
DISABLE_CORRECTION="true"

# Display red dots while waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="taybalt-custom"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$DOTFILES/configs

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git git-extras colorize httpie github npm vagrant)

# Configure zsh options #######################################################
setopt autolist       # Display completion candidates immediately.
setopt cdablevars     # When an argument should be a dir but is not one,
                      # expand it as if it started with ~ (see below).
setopt autonamedirs   # Any parameter that is set to an abosolute directory
                      # name automatically becomes a name for that directory
                      # in the form ~param.
setopt histignoredups # Do not record a command in the history if it is a
                      # duplicate of the previous one.
setopt listtypes      # When listing files that are possible completions,
                      # indicate their types with a trailing character.
setopt nolistbeep     # No bell on ambiguous completion!!

# I like my slow locomotive.
unalias sl > /dev/null 2>&1

# Use VI mode.
bindkey -v
bindkey '^R' history-incremental-search-backward

# Adjust widget behaviors. ####################################################
# While selecting from menu completion, pressing enter accepts the selection
# and executes the command.
# bindkey -M menuselect '^M' .accept-line

function nicediff {
  diff -W `tput cols` -y "$@" | colordiff | less
}
# Activate Oh-My-Zsh
source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

## Emacs:
export EDITOR="$HOME/bin/editor"
export VISUAL="$HOME/bin/editor"
alias e="$EDITOR"
export ALTERNATE_EDITOR=""
export VISUAL="emacsclient"

if [ -f "$HOME/.zshrc_$MY_LOCATION" ]; then
  source "$HOME/.zshrc_$MY_LOCATION"
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

#aliases going below here, would be nice if they were in their own file but
# it was being loaded too early for some reason
# Directories
alias dotfiles="cd $DOTFILES"
alias library="cd $HOME/Library"
alias sites="cd $HOME/Sites"
alias workspace="cd $HOME/workspace"
alias ioc="cd $HOME/workspace/iofficeconnect"
alias iomisc="cd $HOME/workspace/iofficemisc"
alias iorepos="cd $HOME/workspace/iofficerepos"
alias iotxt="cd $HOME/workspace/iofficerepos/text-service"
alias ioai="cd $HOME/workspace/iofficerepos/applicationInfoService"
alias ioauth="cd $HOME/workspace/iofficerepos/auth-service"
alias iokafka="cd $HOME/workspace/iofficerepos/metamorphosis"
alias ioge="cd $HOME/workspace/iofficerepos/ge-current-service"
alias iosensors="cd $HOME/workspace/iofficerepos/sensor-service"
alias ioprefs="cd $HOME/workspace/iofficerepos/pref-service"
alias iogate="cd $HOME/workspace/iofficerepos/gateway-service"
alias iovisitor="cd $HOME/workspace/iofficerepos/visitorApi"
alias ioexchange="cd $HOME/workspace/iofficerepos/EwsService"
alias iolobby="cd $HOME/workspace/iofficerepos/lobbyconnect-webhook-service"

# Vagrant
alias v="vagrant global-status"
alias vup="vagrant up"
alias vhalt="vagrant halt"
alias vssh="vagrant ssh"
alias vreload="vagrant reload"
alias vrebuild="vagrant destroy --force && vagrant up"

## Tmux:
alias ta="tmux attach"
alias tad="tmux attach -d"
alias tl="tmux ls"
alias urldecode='python -c "import sys, urllib as ul; print ul.unquote_plus(sys.argv[1])"'
alias ssh='ssh -A'
alias cpr="rsync -aP"

command -v xdg-open >/dev/null 2>&1 && alias open="xdg-open"

## Emacs:
export EDITOR="$HOME/bin/editor"
export VISUAL="$HOME/bin/editor"
alias e="$EDITOR"
export ALTERNATE_EDITOR=""
export VISUAL="emacsclient"

## SBT
export SBT_OPTS="-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=2G -Xss2M"

## Ensime
alias ensime="ctags -Re . && sbt clean ensimeConfig test:compile ensimeServerIndex"

if [ -f "$HOME/.zshrc_$MY_LOCATION" ]; then
  source "$HOME/.zshrc_$MY_LOCATION"
fi

# OS X things.
if [[ `uname` == "Darwin" ]]; then
  function top() {
    if [ $# -eq 0 ]; then
      /usr/bin/top -o cpu
    else
      /usr/bin/top "$@"
    fi
  }

  # Always use:
  #   l: List in long format
  #   h: Sizes in human-readable form
  #   F: Dir, symlink, executable, etc., symbols
  #   G: Colorize!
  alias l="ls -lhFG"
  alias la="ls -lhFGA"   # All files
  alias ltr="ls -lhFGtr" # By time, reverse
  alias lsr="ls -lhFGSr" # By size, reverse
else
  # Non-OS X things.
  alias l="ls -lhF --group-directories-first --color=always"
fi

# Shortcuts
alias copyssh="pbcopy < $HOME/.ssh/id_rsa.pub"
alias reloadcli="source $HOME/.zshrc"
alias reloaddns="dscacheutil -flushcache && sudo killall -HUP mDNSResponder"
alias ll="$(brew --prefix coreutils)/libexec/gnubin/ls -ahlF --color --group-directories-first"
alias weather="curl -4 http://wttr.in"
alias shrug="echo '¯\_(ツ)_/¯' | pbcopy"

#iOffice
export VISITOR_SERVICE_CLIENT_CODE=aa436ea24e167689cbde035f9ad75e1a
export VISITOR_SERVICE_CLIENT_SECRET=16356d0cb0c8b8117cbc2e7e39397f4bdf499ec2
export PREFERENCE_SERVICE_CLIENT_CODE=G3e8nOrFJnG1LiOWceLxY7au5eV
export PREFERENCE_SERVICE_CLIENT_SECRET=zi5QNIY0THY1EfqkMYzsmFlr0swSaoPPrming6Luyzdl8qT
export SENSOR_SERVICE_CLIENT_CODE=G3e8nOrFJnG1LiOWceLxY7au5eV
export SENSOR_SERVICE_CLIENT_SECRET=zi5QNIY0THY1EfqkMYzsmFlr0swSaoPPrming6Luyzdl8qT
export LOG_LEVEL=INFO
export LOGGER_TEMPLATE={15}
export MESOS_URL=http://mesos.rs.corp.iofficecorp.com
export MARATHON_URL=http://mesos16.rs.corp.iofficecorp.com:8080
export DEV_SCHEMA_REGISTRY_URL=http://mesosdev.rs.corp.iofficecorp.com/kafka/schema-registry
export DEV_BROKERS=91316558-kafka0.pub.va.eventador.io:9092
export PROD_SCHEMA_REGISTRY_URL=http://mesos.rs.corp.iofficecorp.com/kafka/schema-registry
export PROD_BROKERS=40f2dbc2-kafka0.pub.va.eventador.io:9092,40f2dbc2-kafka1.pub.va.eventador.io:9092,40f2dbc2-kafka2.pub.va.eventador.io:9092
export KAFKA_BROKERS=$DEV_BROKERS
export KAFKA_SCHEMA_REGISTRY_URL=$DEV_SCHEMA_REGISTRY_URL
export TWILIO_ROOT_ACCID=AC968b5127f9aca7317f009fbbd7d236c2
export TWILIO_ROOT_ACCTOKEN=5c376e94d36bdba73f3851af180eceb7
export TEXT_SERVICE_CALLBACK_URL=http://7cfe663b.ngrok.io
export TEXT_SERVICE_PROXY_DURATION="2 minutes"
